### PR TITLE
Hyprland - add AQ_DRM_DEVICES to UWSM_FINALIZE_VARNAMES

### PR DESCRIPTION
**Pull request by izmyname**
closes https://github.com/Vladimir-csp/uwsm/issues/61

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
It is a var that Hyprland needs to see, or Hyprland sets and other apps need to see?

**Comment by izmyname** [comment]
It's `aquamarine` var to 'tell' Hyprland, what GPU it must use for rendering itself, so I suppose the former.

**Comment by Vladimir-csp** [comment]
Then it is not the place to put it. 

There is a description for variable placement in https://github.com/Vladimir-csp/uwsm#concepts-and-features under "Idempotently (well, best-effort-idempotently) handles environment."

I probably need to move to somewhere linkable... Repeating it here:

Summary of where to put a user-level var:
- For entire user's context: define in `${XDG_CONFIG_HOME}/environment.d/*.conf`
  (see `man 5 environment.d`)
- For login session context and uwsm environment preloader, including plugins:
  export in `~/.profile` (may have caveats, see your shell's manual)
- For uwsm-managed graphical session: export in `${XDG_CONFIG_HOME}/uwsm/env`
- For uwsm-managed graphical session of specific compositor: export in
  `${XDG_CONFIG_HOME}/uwsm/env-${desktop}`

User needs to define this var anywhere above.

**Comment by izmyname** [comment]
I see.

> * For uwsm-managed graphical session of specific compositor: export in
>       `${XDG_CONFIG_HOME}/uwsm/env-${desktop}`

This looks like the best place to put it. Thanks!

**Pull request closed without merging**
