### PR TITLE
Hyprland & nix patches

### PR DESCRIPTION
**Pull request by kai-tub**
Hey :wave: 
I really like this project and have been using it to manage my Hyprland instance.
Thanks for working on it!

I have updated to the latest release and had to fix the following problems to get it back up and running.
The commit messages should provide the full context but in short, I have:
- Ensured in some places that the full path is used
- Fixed a bug where `Hyprland` (`id`) was searched in the PATH and not `hyprland` (`bin_id`)

Let me know if I should update/rewrite anything!

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
Hi.
`bin_id` is a normalized function-friendly lowercase string for identifying plugins. `id` is the name of the actual executable or Destkop Entry ID.

If your installation of Hyprland has its executable named `Hyprland` and wayland-sessions Desktop Entry named `hyprland.desktop`, then either `uwsm start Hyprland` or `uwsm start hyprland.desktop` should work.

If executables are not in PATH, or PATH known to systemd user daemon lacks a dir where they reside, something might be wrong with your setup.

**Comment by kai-tub** [comment]
Hey,
> bin_id is a normalized function-friendly lowercase string for identifying plugins. id is the name of the actual executable or Destkop Entry ID.

Sorry! Yeah, I misunderstood how the `start` command works and confused myself with an invalid custom desktop entry. But for completeness, the executable is named `hyprland` (lower-case), as well as the _default_ desktop entry (`hyprland.desktop`).

> If executables are not in PATH, or PATH known to systemd user daemon lacks a dir where they reside, something might be wrong with your setup.

Hmm. I believe this is one of the cases where I have to admit that I am using NixOS and at least for _NixOS_ these patches are required. :sweat_smile: 
A core principle of Nix is that all applications and their dependencies are tracked independently from one another.
So if `uwsm` requires `waitpid` (`util-linux`), only the specific version that is linked to the build of `uwsm` should be used for the execution of `uwsm`. But it should not taint the environment for other applications, as this allows them to use their own `util-linux` version if necessary.

Concretely, this means that I am building `uwsm` and wrapping it inside of a script that makes these build dependencies available in the PATH during the execution of `uwsm`. So when `which` is called from within `uwsm`, `waitpid` is available in the PATH. But if the service unit is started, it won't have the same PATH and will be missing `waitpid` (as there might also be multiple versions of it).
This PATH _wrapping_ is also recommended for packaging such applications on the NixOS side.

Independently from NixOS, adding the full path in the subprocess call is also recommended in the Python documentation (https://docs.python.org/3/library/subprocess.html#popen-constructor), and providing a full path for the service units is not uncommon either.
Also, since these are transient units and runtime executions, I do not see any issues for 'normal' distributions even if the code underlying dependencies are updated, at least, AFAIK.

However, I can understand if you dislike having distro-specific "work-arounds" in the code that might seem unnecessary otherwise.

If this message doesn't convince you, I would package `uwsm` for nix and always apply these patches on top during build time to "fix" it for NixOS, which is also not that uncommon.

Thanks for considering this PR and providing quick feedback!

**Comment by Vladimir-csp** [comment]
I am aware that uwsm is used on Nix, maybe somebody already solved it.
But I'll consider fixes on this side, thanks!

**Comment by kai-tub** [comment]
I mean by applying these patches during the build phase they are "solved on Nix". 
So it isn't too much work to maintain these patches 👍 

I will clean up my flake within this week and would create a pr to link to that repo once it is finished, as the current link is archived/unmaintained; I would love to support the nix side and also have CI tests for Hyprland. :)

Thanks again for the project!

**Comment by JohnRTitor** [comment]
`uwsm` is now packaged on nixpkgs (https://github.com/NixOS/nixpkgs/pull/329582). Should be available on both nixos-unstable and 24.05 release in a week or so.

@kai-tub I took a look at your implementation and decided to make a NixOS module (https://github.com/JohnRTitor/nix-conf/commit/642754a8c50a27e8c2ce2483606fad422b4c560d).

It does not work at the moment and I can't figure out why. If you could use that and make a PR upstream I would be grateful!

**Comment by JohnRTitor** [comment]
Another thing @Vladimir-csp, does `uwsm start` allow the path of the WM to be passed directly?
Like:
```bash
uwsm start -N "My compositor" -D mycompositor -C "My cool compositor" /usr/bin/mywm
```

This could help us on the nix side where we would need to maintain multiple uwsm versions (one for Sway, one for Hyprland etc) otherwise.

**Comment by kai-tub** [comment]
Hey, I believe if #35 is allowed, there might be a way to use the _default_ `.desktop` entries (as commented in https://github.com/NixOS/nixpkgs/pull/330245). But I agree that it would be nicer to have support for full paths, also [since the desktop entry specification allows full paths](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html)

> The executable program can either be specified with its full path or with the name of the executable only.

it might be surprising to see that `uwsm` does not support full paths (it was at least surprising to me).

Either way, we will find a solution on the nix side :+1:

**Comment by Vladimir-csp** [comment]
The concept with units was to be as generic as possible and pass executables/entries as specifiers. Only when arguments are requested, they are saved in drop-ins. 
I could add an option to also save paths in drop-ins.

Not sure how to deal with `sh` path suggested in this PR, it does not make much sense, since finding sh path in `uwsm start` will not affect env preloader unit  in any way. Maybe it will require saving it in drop-in with `Environment=` key.

**Comment by kai-tub** [comment]
Regarding the `sh` suggestion. I believe it is the other way around. I need to provide the path of `sh` into the `subprocess.run` command, as the new environment `env_pre` does _not_ contain the PATH to `sh`. So we the subprocess is executed, it cannot resolve `sh`.

I have attached a log with DEBUG=1 started via `uwsm start select`, maybe this provides some additional insights:

<details>
<summary> Logs </summary>

```
node # [   17.087787] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:1696 __init__
node # [   17.090086] uwsm_env-preloader[980]:  parsing argv ['aux', 'prepare-env', 'hyprland.desktop'] exit_on_error: True
node # [   17.090893] uwsm_env-preloader[980]: END_DEBUG
node # [   17.095263] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3886 main
node # [   17.096277] uwsm_env-preloader[980]:  Args.parsed Namespace(mode='aux', aux_action='prepare-env', wm_cmdline=['hyprland.desktop'], desktop_names='', desktop_names_exclusive=False, wm_name='', wm_comment='')
node # [   17.097588] uwsm_env-preloader[980]: END_DEBUG
node # [   17.098656] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:4260 main
node # [   17.100961] uwsm_env-preloader[980]:  manager_pid: 952, ppid: 952
node # [   17.101504] uwsm_env-preloader[980]: END_DEBUG
node # [   17.101841] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3607 fill_wm_globals
node # [   17.102686] uwsm_env-preloader[980]:  Compositor ID is a Desktop Entry: hyprland.desktop
node # [   17.103298] uwsm_env-preloader[980]: END_DEBUG
node # [   17.103657] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:673 find_entries
node # [   17.104543] uwsm_env-preloader[980]:  searching entries in wayland-sessions
node # [   17.105181] uwsm_env-preloader[980]: END_DEBUG
node # [   17.107134] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:706 find_entries
node # [   17.109048] uwsm_env-preloader[980]:  considering hyprland_uwsm.desktop /nix/store/6j1rij2bwh8gibm6darmwkj3wl0k06js-desktops/share/wayland-sessions/hyprland_uwsm.desktop
node # [   17.110154] uwsm_env-preloader[980]: END_DEBUG
node # [   17.110510] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:565 entry_parser_by_ids
node # [   17.111422] uwsm_env-preloader[980]:  not an entry we are looking for
node # [   17.111898] uwsm_env-preloader[980]: END_DEBUG
node # [   17.112959] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:706 find_entries
node # [   17.113838] uwsm_env-preloader[980]:  considering hyprland.desktop /nix/store/6j1rij2bwh8gibm6darmwkj3wl0k06js-desktops/share/wayland-sessions/hyprland.desktop
node # [   17.114798] uwsm_env-preloader[980]: END_DEBUG
node # [   17.118300] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:460 check_entry_basic
node # [   17.119382] uwsm_env-preloader[980]: entry "/nix/store/6j1rij2bwh8gibm6darmwkj3wl0k06js-desktops/share/wayland-sessions/hyprland.desktop"
node # [   17.120392] uwsm_env-preloader[980]:   all clear
node # [   17.120744] uwsm_env-preloader[980]: END_DEBUG
node # [   17.123044] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:576 entry_parser_by_ids
node # [   17.123908] uwsm_env-preloader[980]:  matched and checked
node # [   17.124369] uwsm_env-preloader[980]: END_DEBUG
node # [   17.124706] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3623 fill_wm_globals
node # [   17.125590] uwsm_env-preloader[980]:  entry Hyprland
node # [   17.126094] uwsm_env-preloader[980]: END_DEBUG
node # [   17.128151] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3630 fill_wm_globals
node # [   17.129054] uwsm_env-preloader[980]:  self_name: uwsm
node # [   17.129468] uwsm_env-preloader[980]: wm_cmdline[0]: Hyprland
node # [   17.129924] uwsm_env-preloader[980]: END_DEBUG
node # [   17.130518] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3686 fill_wm_globals
node # [   17.131600] uwsm_env-preloader[980]:  CompGlobals.cmdline ['Hyprland']
node # [   17.132215] uwsm_env-preloader[980]: END_DEBUG
node # [   17.134278] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:1061 is_active
node # [   17.135359] uwsm_env-preloader[980]:  bus_session initial DbusInteractions, instance level: session, instance objects:
node # [   17.136063] uwsm_env-preloader[980]: {'bus': <dbus._dbus.SessionBus (session) at 0x7f2b9b35ea50>}
node # [   17.136727] uwsm_env-preloader[980]: END_DEBUG
node # [   17.141043] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:3749 fill_wm_globals
node # [   17.141966] uwsm_env-preloader[980]:  CompGlobals.desktop_names ['Hyprland']
node # [   17.142476] uwsm_env-preloader[980]: END_DEBUG
node # [   17.142811] uwsm_env-preloader[980]: Preparing environment for Hyprland...
node # [   17.143360] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:2610 prepare_env
node # [   17.144227] uwsm_env-preloader[980]:  bus_session initial DbusInteractions, instance level: session, instance objects:
node # [   17.144957] uwsm_env-preloader[980]: {'bus': <dbus._dbus.SessionBus (session) at 0x7f2b9b35ea50>}
node # [   17.145595] uwsm_env-preloader[980]: END_DEBUG
node # [   17.164065] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:2297 get_session_by_vt
node # [   17.165028] uwsm_env-preloader[980]:  CompletedProcess(args=['loginctl', 'list-sessions', '--no-legend', '--no-pager'], returncode=0, stdout='1 1000 kai seat0 tty1\n', stderr='')
node # [   17.166062] uwsm_env-preloader[980]: END_DEBUG
node # [   17.166448] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:2309 get_session_by_vt
node # [   17.167333] uwsm_env-preloader[980]:  session_id 1
node # [   17.167700] uwsm_env-preloader[980]: END_DEBUG
node # [   17.172866] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:2328 get_session_by_vt
node # [   17.174211] uwsm_env-preloader[980]:  CompletedProcess(args=['loginctl', 'show-session', '1', '--property', 'Name', '--property', 'VTNr'], returncode=0, stdout='Name=kai\nVTNr=1\n', stderr='')
node # [   17.175552] uwsm_env-preloader[980]: END_DEBUG
node # [   17.178912] uwsm_env-preloader[980]: [Errno 2] No such file or directory: 'sh'
node # [   17.190657] uwsm_env-preloader[980]: Traceback (most recent call last):
node # [   17.191906] uwsm_env-preloader[980]:   File "/nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py", line 4268, in main
node # [   17.193074] uwsm_env-preloader[980]:     prepare_env()
node # [   17.195050] uwsm_env-preloader[980]:   File "/nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py", line 2630, in prepare_env
node # [   17.195963] uwsm_env-preloader[980]:     sprc = subprocess.run(
node # [   17.196437] uwsm_env-preloader[980]:            ^^^^^^^^^^^^^^^
node # [   17.196901] uwsm_env-preloader[980]:   File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 548, in run
node # [   17.197805] uwsm_env-preloader[980]:     with Popen(*popenargs, **kwargs) as process:
node # [   17.198531] uwsm_env-preloader[980]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
node # [   17.199101] uwsm_env-preloader[980]:   File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 1026, in __init__
node # [   17.200049] uwsm_env-preloader[980]:     self._execute_child(args, executable, preexec_fn, close_fds,
node # [   17.200673] uwsm_env-preloader[980]:   File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 1955, in _execute_child
node # [   17.201613] uwsm_env-preloader[980]:     raise child_exception_type(errno_num, err_msg, err_filename)
node # [   17.202244] uwsm_env-preloader[980]: FileNotFoundError: [Errno 2] No such file or directory: 'sh'
node # [   17.202839] uwsm_env-preloader[980]: Cleaning up...
node # [   17.203230] uwsm_env-preloader[980]: DEBUG /nix/store/ivn6kli9qdh7nljima71qwb42nhlbaan-uwsm/share/uwsm/modules/uwsm/main.py:2771 cleanup_env
node # [   17.204276] uwsm_env-preloader[980]:  bus_session initial DbusInteractions, instance level: session, instance objects:
node # [   17.205178] uwsm_env-preloader[980]: {'bus': <dbus._dbus.SessionBus (session) at 0x7f2b9b35ea50>}
node # [   17.205760] uwsm_env-preloader[980]: END_DEBUG
node # [   17.206268] uwsm_env-preloader[980]: No cleanup files found.
node # [   17.219481] systemd[952]: wayland-wm-env@hyprland.desktop.service: Main process exited, code=exited, status=1/FAILURE
node # [   17.220788] systemd[952]: wayland-wm-env@hyprland.desktop.service: Failed with result 'exit-code'.
node # [   17.221695] systemd[952]: Failed to start Environment preloader for Hyprland.
node # [   17.222595] systemd[952]: Dependency failed for Main service for Hyprland, An intelligent dynamic tiling Wayland compositor.
node # [   17.238257] systemd[952]: wayland-wm@hyprland.desktop.service: Job wayland-wm@hyprland.desktop.service/start failed with result 'dependency'.
node # [   17.239429] systemd[952]: wayland-wm@hyprland.desktop.service: Triggering OnFailure= dependencies.
node # [   17.240103] systemd[952]: wayland-wm-env@hyprland.desktop.service: Triggering OnFailure= dependencies.
node # [   17.241940] systemd[952]: Reached target Shutdown graphical session units.
node # [   17.246462] systemd[952]: Stopped target Shutdown graphical session units.
node # [   17.250274] systemd[952]: wayland-session-bindpid@969.service: Triggering OnSuccess= dependencies.
node # [   17.251889] systemd[952]: Reached target Shutdown graphical session units.
node # [   17.252547] systemd[952]: Stopped target Shutdown graphical session units.

```
</details>

**Comment by Vladimir-csp** [comment]
Does a wrapper script always replace original uwsm in a Nix installation? That is, when a unit runs `uwsm ...`, does it actually execute a wrapper?

**Comment by JohnRTitor** [comment]
> Does a wrapper script always replace original uwsm in a Nix installation? That is, when a unit runs `uwsm ...`, does it actually execute a wrapper?

Yes.

**Comment by Vladimir-csp** [comment]
Thanks!
I'll wait a bit on an unrelated [feature request](https://github.com/hyprwm/Hyprland/issues/7083) in Hyprland, then tag a new version.

So with this merged, and #35 fixed, should I bother with compositor path saving, or is the current state enough?

**Comment by JohnRTitor** [comment]
>  should I bother with compositor path saving, or is the current state enough?

Yes, being able to call a compositor by its absolute path would make our job significantly easier.

**Comment by Vladimir-csp** [comment]
Do wayland-sessions desktop entry paths themselves require any special treatment, or only executable paths?

Do wayland-sessions desktop entries packaged in Nix contain paths in their `Exec=`?

**Comment by JohnRTitor** [comment]
> Do wayland-sessions desktop entries packaged in Nix contain paths in their `Exec=`?

Not always. But it'll definitely make our job easier to handle it on the nix side to be able to use paths, to desktop entries or compositors.

image

**Comment by Vladimir-csp** [comment]
Is `$XDG_DATA_DIRS` modified for display managers (or uwsm) to find those entries?

**Comment by JohnRTitor** [comment]
XDG_DATA_DIRS are indeed modified. The below output is from a user/normal terminal.

But XDG_DATA_DIRS is not exported to early environment (before WM, at DM) AFAIK.

❯  echo $XDG_DATA_DIRS 
/nix/store/rayaaq8j5ikbgzlqm3hv45rzv692fyw1-desktops/share:/home/masum/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/home/masum/.nix-profile/share:/home/masum/.local/state/nix/profile/share:/home/masum/.local/state/nix/profile/share:/etc/profiles/per-user/masum/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share

❯  tree /nix/store/rayaaq8j5ikbgzlqm3hv45rzv692fyw1-desktops/share
/nix/store/rayaaq8j5ikbgzlqm3hv45rzv692fyw1-desktops/share
├── wayland-sessions
│   ├── hyprland.desktop -> /nix/store/m3362j6js949ahgv2lfm5pyhv3zc24xv-hyprland-0.41.2/share/wayland-sessions/hyprland.desktop
│   └── Hyprland_uwsm.desktop -> /nix/store/ga2zcg205mqm040hxmn244aqv3iskk19-Hyprland_uwsm-1.0.0/share/wayland-sessions/Hyprland_uwsm.desktop
└── xsessions

3 directories, 2 files

**Comment by Vladimir-csp** [comment]
> But XDG_DATA_DIRS is not exported to early environment (before WM, at DM) AFAIK.

Then how would DM find any sessions?

**Comment by JohnRTitor** [comment]
Not sure, perhaps @jtojnar would be able to provide some intel.

**Comment by Vladimir-csp** [comment]
Try 6ce6b9b68bbd78996bd3ff8ba402485e5418e673.

**Comment by JohnRTitor** [comment]
Sweet, starting with

```bash
uwsm start -S /run/booted-system/sw/bin/Hyprland;
```

works!

**Comment by kai-tub** [comment]
Hey, sorry to disturb you again @Vladimir-csp.
The patch in https://github.com/Vladimir-csp/uwsm/commit/6ce6b9b68bbd78996bd3ff8ba402485e5418e673 doesn't work as expected.
The issue lies here:

https://github.com/Vladimir-csp/uwsm/blob/6ce6b9b68bbd78996bd3ff8ba402485e5418e673/uwsm/main.py#L3827-L3830

Now, if a full PATH is provided, it still checks if `Hyprland` is available and fails in this case.

I tried a couple of variants to fix the problem, but I cannot really understand how the different variables are constructed and where the values are set/re-parsed. 
Disabling this check definitely solves the issue though :sweat_smile: 

> Then how would DM find any sessions?

yeah, I am also not sure how it works in the other cases :/
I will investigate and report back once :+1:

**Comment by JohnRTitor** [comment]
> Now, if a full PATH is provided, it still checks if `Hyprland` is available and fails in this case.
I can reproduce the problem. That's why it was failing without wrapping with `hyprland`.

**Comment by jtojnar** [comment]
> Then how would DM find any sessions?

We either pass the path to the symlink tree containing the desktop files to DM configuration:

https://github.com/NixOS/nixpkgs/blob/3a2592ce1e8c3cb79695838a8d45076b8e663e56/nixos/modules/services/x11/display-managers/lightdm.nix#L47
https://github.com/NixOS/nixpkgs/blob/3a2592ce1e8c3cb79695838a8d45076b8e663e56/nixos/modules/services/display-managers/sddm.nix#L71

Or, in case of GDM, explicitly pass the environment variable to `display-manager.service`:

https://github.com/NixOS/nixpkgs/blob/3a2592ce1e8c3cb79695838a8d45076b8e663e56/nixos/modules/services/x11/display-managers/gdm.nix#L157

**Comment by Vladimir-csp** [comment]
> Now, if a full PATH is provided, it still checks if Hyprland is available and fails in this case.

Should be fixed. Please provide further feedback in #36.

**Pull request merged**
